---
# tasks file for roles/nginx_frontend
- name: Install Nginx
  apt:
    name: nginx
    state: present
  become: true

- name: Ensure Nginx is running and enabled
  service:
    name: nginx
    state: started
    enabled: yes
  become: true

- name: Copy Nginx configuration file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  become: true
  notify:
    - Restart Nginx
  become: true
